const preset = {
  theme: {
    extend: {
      colors: {
        background: "var(--ml-color-background)",
        foreground: "var(--ml-color-foreground)",
        gray: {
          50: "var(--ml-color-gray-50)",
          100: "var(--ml-color-gray-100)",
          200: "var(--ml-color-gray-200)",
          300: "var(--ml-color-gray-300)",
          400: "var(--ml-color-gray-400)",
          500: "var(--ml-color-gray-500)",
          600: "var(--ml-color-gray-600)",
          700: "var(--ml-color-gray-700)",
          800: "var(--ml-color-gray-800)",
          900: "var(--ml-color-gray-900)",
          950: "var(--ml-color-gray-950)",
        },
        mage: {
          50: "var(--ml-color-mage-50)",
          100: "var(--ml-color-mage-100)",
          200: "var(--ml-color-mage-200)",
          300: "var(--ml-color-mage-300)",
          400: "var(--ml-color-mage-400)",
          500: "var(--ml-color-mage-500)",
          600: "var(--ml-color-mage-600)",
          700: "var(--ml-color-mage-700)",
          800: "var(--ml-color-mage-800)",
          900: "var(--ml-color-mage-900)",
        },
        primary: "var(--ml-color-primary)",
        "primary-foreground": "var(--ml-color-primary-foreground)",
        secondary: "var(--ml-color-secondary)",
        "secondary-foreground": "var(--ml-color-secondary-foreground)",
        muted: "var(--ml-color-muted)",
        "muted-foreground": "var(--ml-color-muted-foreground)",
        accent: "var(--ml-color-accent)",
        "accent-foreground": "var(--ml-color-accent-foreground)",
        card: "var(--ml-color-card)",
        "card-foreground": "var(--ml-color-card-foreground)",
        popover: "var(--ml-color-popover)",
        "popover-foreground": "var(--ml-color-popover-foreground)",
        border: "var(--ml-color-border)",
        input: "var(--ml-color-input)",
        ring: "var(--ml-color-ring)",
        success: "var(--ml-color-success)",
        warning: "var(--ml-color-warning)",
        error: "var(--ml-color-error)",
      },
      fontFamily: {
        sans: ["var(--ml-font-sans)"],
        mono: ["var(--ml-font-mono)"],
        accent: ["var(--ml-font-accent)"],
      },
      borderRadius: {
        sm: "var(--ml-radius-sm)",
        md: "var(--ml-radius-md)",
        lg: "var(--ml-radius-lg)",
        xl: "var(--ml-radius-xl)",
        "2xl": "var(--ml-radius-2xl)",
        "3xl": "var(--ml-radius-3xl)",
      },
      boxShadow: {
        sm: "var(--ml-shadow-sm)",
        md: "var(--ml-shadow-md)",
        lg: "var(--ml-shadow-lg)",
        xl: "var(--ml-shadow-xl)",
      },
      maxWidth: {
        "container-md": "var(--ml-container-md)",
        "container-lg": "var(--ml-container-lg)",
        "container-xl": "var(--ml-container-xl)",
      },
      letterSpacing: {
        eyebrow: "var(--ml-letter-spacing-eyebrow)",
      },
      transitionTimingFunction: {
        emphasized: "var(--ml-ease-emphasized)",
      },
      transitionDuration: {
        fast: "var(--ml-duration-fast)",
        base: "var(--ml-duration-base)",
        slow: "var(--ml-duration-slow)",
      },
      zIndex: {
        base: "var(--ml-z-base)",
        sticky: "var(--ml-z-sticky)",
        dropdown: "var(--ml-z-dropdown)",
        overlay: "var(--ml-z-overlay)",
        modal: "var(--ml-z-modal)",
      },
    },
  },
};

export default preset;
