import { mkdir, readFile, writeFile } from "node:fs/promises";

const sourcePath = new URL("../tokens/tokens.source.json", import.meta.url);
const cssPath = new URL("../src/tokens.css", import.meta.url);
const jsonPath = new URL("../src/tokens.json", import.meta.url);

const raw = await readFile(sourcePath, "utf8");
const source = JSON.parse(raw);

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function camelToKebab(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function toCssPath(path) {
  if (path[0] === "meta") {
    return null;
  }

  if (path[0] === "typography") {
    if (path[1] === "font") {
      return ["font", ...path.slice(2)];
    }
    if (path[1] === "size") {
      return ["font-size", ...path.slice(2)];
    }
    if (path[1] === "lineHeight") {
      return ["line-height", ...path.slice(2)];
    }
    if (path[1] === "letterSpacing") {
      return ["letter-spacing", ...path.slice(2)];
    }
  }

  if (path[0] === "layout") {
    if (path[1] === "container") {
      return ["container", ...path.slice(2)];
    }
    if (path[1] === "borderWidth") {
      return ["border-width", ...path.slice(2)];
    }
  }

  if (path[0] === "motion") {
    return [...path.slice(1)];
  }

  if (path[0] === "zIndex") {
    return ["z", ...path.slice(1)];
  }

  return path;
}

function flattenObject(input, prefix = []) {
  const entries = [];

  for (const [key, value] of Object.entries(input)) {
    const nextPath = [...prefix, key];
    if (isObject(value)) {
      entries.push(...flattenObject(value, nextPath));
    } else {
      entries.push([nextPath, value]);
    }
  }

  return entries;
}

function deepMerge(base, override) {
  const result = structuredClone(base);

  for (const [key, value] of Object.entries(override)) {
    if (isObject(value) && isObject(result[key])) {
      result[key] = deepMerge(result[key], value);
    } else {
      result[key] = value;
    }
  }

  return result;
}

function getPathValue(object, path) {
  return path.split(".").reduce((current, segment) => current?.[segment], object);
}

function resolveReferences(input, root) {
  if (isObject(input)) {
    return Object.fromEntries(
      Object.entries(input).map(([key, value]) => [key, resolveReferences(value, root)]),
    );
  }

  if (typeof input === "string") {
    const exact = input.match(/^\{([^}]+)\}$/);
    if (exact) {
      const resolved = getPathValue(root, exact[1]);
      if (resolved === undefined) {
        throw new Error(`Unresolved token reference: ${input}`);
      }
      return resolved;
    }

    return input.replace(/\{([^}]+)\}/g, (_, ref) => {
      const resolved = getPathValue(root, ref);
      if (resolved === undefined) {
        throw new Error(`Unresolved token reference: {${ref}}`);
      }
      return String(resolved);
    });
  }

  return input;
}

function toCssVars(object) {
  return flattenObject(object)
    .map(([path, value]) => [toCssPath(path), value])
    .filter(([path]) => path !== null)
    .map(([path, value]) => `  --ml-${path.map(camelToKebab).join("-")}: ${value};`)
    .join("\n");
}

const defaultThemeName = "dark";
const shared = source.shared;
const themes = {};

for (const [themeName, themeConfig] of Object.entries(source.themes)) {
  const merged = deepMerge(shared, themeConfig);
  const resolved = resolveReferences(merged, merged);
  themes[themeName] = resolved;
}

const defaultTheme = themes[defaultThemeName];

const cssBlocks = [];
cssBlocks.push("/* This file is generated by `node scripts/build-tokens.mjs`. */");
cssBlocks.push(":root {");
cssBlocks.push(`  color-scheme: ${defaultTheme.meta.colorScheme};`);
cssBlocks.push(toCssVars(defaultTheme));
cssBlocks.push("}");

for (const [themeName, tokens] of Object.entries(themes)) {
  if (themeName === defaultThemeName) {
    cssBlocks.push("");
    cssBlocks.push(':root[data-theme="dark"], [data-theme="dark"] {');
  } else {
    cssBlocks.push("");
    cssBlocks.push(`[data-theme="${themeName}"] {`);
  }
  cssBlocks.push(`  color-scheme: ${tokens.meta.colorScheme};`);
  cssBlocks.push(toCssVars(tokens));
  cssBlocks.push("}");
}

const outputJson = {
  source: "tokens/tokens.source.json",
  defaultTheme: defaultThemeName,
  shared,
  themes,
};

await mkdir(new URL("../src/", import.meta.url), { recursive: true });
await writeFile(cssPath, `${cssBlocks.join("\n")}\n`);
await writeFile(jsonPath, `${JSON.stringify(outputJson, null, 2)}\n`);

console.log("tokens built");
